#!/usr/bin/env python3
"""Regenerate STATE.md from the actual repositories.

Session continuity fails when the handover document is written from memory.
This reads the working trees instead: branch, cleanliness, last commit, gate
status. It is run at session end and by CI, so the next session reads fact.

Usage:
    python3 tools/handoff.py [--fleet DIR] [--check]

--check exits non-zero if STATE.md is out of date, for use as a CI gate.
"""
from __future__ import annotations

import argparse
import datetime
import os
import subprocess
import sys

# Product repositories ship to users and pass the release gate.
PRODUCT = [
    "shesh-core", "shesh-memory", "shesh-orchestrator", "shesh-harness",
    "shesh-phone", "shesh-omniroute", "shesh-skills", "shesh-voice",
    "shesh-desktop", "SheshAOS",
]
# Composition: the manifest and the gates that resolve it.
COMPOSITION = ["shesh-ecosystem"]
# Factory tooling never reaches a user's machine.
FACTORY = ["shesh-workspace"]
# Documentation and records.
DOCS = ["shesh-docs", "shesh-docs-archive"]


def git(repo: str, *args: str) -> str:
    try:
        return subprocess.run(
            ["git", "-C", repo, *args],
            capture_output=True, text=True, timeout=30,
        ).stdout.strip()
    except (subprocess.SubprocessError, OSError):
        return ""


def survey(fleet: str, name: str) -> dict | None:
    repo = os.path.join(fleet, name)
    if not os.path.isdir(os.path.join(repo, ".git")):
        return None
    dirty = [ln for ln in git(repo, "status", "--porcelain").splitlines() if ln]
    return {
        "name": name,
        "branch": git(repo, "rev-parse", "--abbrev-ref", "HEAD") or "?",
        "head": git(repo, "rev-parse", "--short", "HEAD") or "?",
        "subject": git(repo, "log", "-1", "--pretty=%s") or "",
        "when": git(repo, "log", "-1", "--pretty=%cs") or "",
        "dirty": len(dirty),
        "untracked": sum(1 for ln in dirty if ln.startswith("??")),
    }


def table(rows: list[dict]) -> list[str]:
    if not rows:
        return ["_None checked out._", ""]
    out = ["| Repository | Branch | Head | Working tree | Last commit |",
           "|---|---|---|---|---|"]
    for r in rows:
        state = "clean" if not r["dirty"] else f"**{r['dirty']} changed**"
        subject = r["subject"][:52].replace("|", r"\|")
        out.append(
            f"| `{r['name']}` | {r['branch']} | `{r['head']}` | {state} "
            f"| {subject} ({r['when']}) |"
        )
    out.append("")
    return out


def render(fleet: str) -> str:
    today = datetime.date.today().isoformat()
    groups = [
        ("Product", "Ships to users. Passes the release gate.", PRODUCT),
        ("Composition", "Manifest, lockfiles, and gates.", COMPOSITION),
        ("Factory", "Build tooling. Never installed by a user.", FACTORY),
        ("Documentation", "Published, not installed.", DOCS),
    ]

    lines = [
        "<!-- Generated by tools/handoff.py. Do not edit by hand. -->",
        "",
        "# STATE.md",
        "",
        f"Fleet state as of **{today}**, read from the working trees rather than",
        "from recollection. Regenerated by `tools/handoff.py` and by CI.",
        "",
        "Start at [HANDOFF.md](HANDOFF.md). This file is the inventory, not the",
        "instructions.",
        "",
    ]

    all_rows = []
    for title, blurb, names in groups:
        rows = [r for r in (survey(fleet, n) for n in names) if r]
        all_rows += rows
        lines += [f"## {title}", "", blurb, ""] + table(rows)

    dirty = [r for r in all_rows if r["dirty"]]
    lines += ["## Work in flight", ""]
    if dirty:
        lines.append("Uncommitted changes are present. Establish whether each is an")
        lines.append("unfinished fix or an abandoned experiment before building on it.")
        lines.append("")
        for r in dirty:
            lines.append(f"- `{r['name']}`: {r['dirty']} changed "
                         f"({r['untracked']} untracked) on `{r['branch']}`")
        lines.append("")
    else:
        lines += ["Every checked-out tree is clean.", ""]

    lines += [
        "## Next",
        "",
        "1. Read [AGENTS.md](AGENTS.md) for the conventions and boundaries.",
        "2. Read [HANDOFF.md](HANDOFF.md) for the work loop and the product",
        "   versus factory split.",
        "3. Take one item from [TODO.md](TODO.md).",
        "4. Run `make check` before you start, so a pre-existing failure is not",
        "   mistaken for yours.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    ap.add_argument("--fleet", default=os.path.dirname(here))
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if STATE.md is stale")
    args = ap.parse_args()

    out = os.path.join(here, "STATE.md")
    new = render(args.fleet)

    if args.check:
        old = ""
        if os.path.exists(out):
            with open(out, encoding="utf-8") as fh:
                old = fh.read()
        # Compare only the stable substance. The date line changes daily, and
        # the working-tree columns are self-referential: writing this file
        # dirties the tree, which changes the file.
        def strip(t: str) -> str:
            keep = []
            for ln in t.splitlines():
                if ln.startswith("Fleet state as of"):
                    continue
                if ln.startswith("| `") or ln.startswith("- `"):
                    continue          # per-repo rows carry volatile state
                if ln.startswith("Uncommitted changes are present") or \
                   ln.startswith("Every checked-out tree is clean"):
                    continue
                keep.append(ln)
            return "\n".join(keep)
        if strip(old) != strip(new):
            print("STATE.md is out of date. Run: python3 tools/handoff.py")
            return 1
        print("STATE.md is current.")
        return 0

    with open(out, "w", encoding="utf-8") as fh:
        fh.write(new)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
